/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103679-g7bbad32d5a-20210918"
#endif /* AVUTIL_FFVERSION_H */
