/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103787-ga487635b85-20210922"
#endif /* AVUTIL_FFVERSION_H */
